package com.example.erp.entity;

// MANUAL: a person created this request by hand (the only path that existed
// before auto-replenishment). AUTO_REORDER: generated by
// PurchaseRequestServiceImpl.generateFromLowStock from the Low Stock report.
public enum PurchaseRequestSource {
    MANUAL,
    AUTO_REORDER
}
